---
apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  annotations:
    autoscaling.knative.dev/target: "10"
  name: llama-31-8b-instruct-2xgpu
  namespace: nim-kserve-pvc
spec:
  predictor:
    annotations:
      prometheus.io/path: /metrics
      prometheus.io/port: "8000"
      serving.knative.openshift.io/enablePassthrough: "true"
      sidecar.istio.io/inject: "true"
      sidecar.istio.io/rewriteAppHTTPProbers: "true"
    minReplicas: 1
    model:
      modelFormat:
        name: llama-31-8b-instruct
      resources:
        limits:
          nvidia.com/gpu: "2"
        requests:
          nvidia.com/gpu: "2"
      runtime: llama-31-8b-instruct
    nodeSelector:
      node.kubernetes.io/instance-type: p4d.24xlarge
    tolerations:
      - effect: NoSchedule
        key: nvidia.com/gpu
        operator: Exists
      - effect: NoSchedule
        key: odh-notebook
        operator: Exists
